// type information is lost at compile time due to erasure. 
// Scala features Manifests, allowing us to selectively recover type information. 
// Manifests are provided as an implicit value, generated by the compiler as needed
class MakeFoo[A](implicit manifest: Manifest[A]) { def make: A = manifest.erasure.newInstance.asInstanceOf[A] }

(new MakeFoo[String]).make